config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tweets, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  paginates_per 25

def self.search(query)
  scope = all
  return scope unless query.present?
  scope = scope.where('text like ?', "%#{query}%")
  scope
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.search(params[:search]).order(tweet_time: :desc).page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterPG4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>'Aleppo' tweets fetcher</h1>
<h2>Auto-refresh every 10 min</h2>

<div class="pagination">
  <%= paginate @tweets %>
</div>
<div class="search-container">
  <%= form_tag tweets_path, method: :get do %>
    <%= label_tag :search %>
    <%= text_field_tag :search, params[:search] %>

    <%= submit_tag "Search", name: nil, class: 'btn btn-success' %>
  <% end %>

  <% if params[:search].present? %>
    <%= link_to "Clear", tweets_path, class: 'btn btn-primary' %>
  <% end %>
</div>

<% @tweets.each do |tweet| %>
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <div class="card mb-4 shadow-sm">
        <div class="card-body">
          <p class="card-text"><strong>@<%= tweet.nickname %></strong></p>
          <p class="card-text"><%= tweet.text %></p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Zobacz cały tweet", tweet.url %></button>
              <small class="text-muted margin-id">ID Tweet: <%= tweet.uuid %> / ID: <%= tweet.id %></small>
            </div>
            <small class="text-muted"><%= tweet.tweet_time %></small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
<div class="pagination">
  <%= paginate @tweets %>
</div>